services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/root/config.yaml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - mock-users
      - mock-orders

  mock-users:
    image: clue/json-server
    ports:
      - "3001:80"
    volumes:
      - ./mock-data/users.json:/data/db.json:ro
    restart: unless-stopped

  mock-orders:
    image: clue/json-server
    ports:
      - "3002:80"
    volumes:
      - ./mock-data/orders.json:/data/db.json:ro
    restart: unless-stopped